import type { TaskConfig } from 'payload'
import { DateTime } from 'luxon'
import { buildDefaultDigestContent, fetchTopDigestArticles } from '@/lib/daily-newsletter'
import type { NewsletterCampaign } from '@/payload-types'

const SOMALIA_TZ = 'Africa/Mogadishu'
const NEWSLETTER_QUEUE = 'newsletter'

type NewsletterCampaignInput = Omit<
  NewsletterCampaign,
  'id' | 'createdAt' | 'updatedAt' | 'sentAt' | 'sentCount' | 'failedCount' | 'errorLog'
>

export const sendDailyDigestTask: TaskConfig<'sendDailyDigest'> = {
  slug: 'sendDailyDigest',
  retries: 1,
  schedule: [
    {
      cron: '0 15 * * *',
      queue: NEWSLETTER_QUEUE,
    },
  ],
  handler: async ({ req }) => {
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://dawan.so'
    const now = DateTime.now().setZone(SOMALIA_TZ)
    const digestDate = now.startOf('day').toISO()

    const topArticles = await fetchTopDigestArticles({ req, siteUrl })

    if (topArticles.length === 0) {
      return {
        output: {
          skipped: true,
        },
      }
    }

    const subject = `5-ta war ee caawa - ${now.toFormat('d LLL yyyy')}`
    const lexicalContent = buildDefaultDigestContent(now)

    const campaignData: NewsletterCampaignInput = {
      subject,
      content: lexicalContent,
      status: 'send_now' as const,
      digestDate,
      autoGenerated: true,
      lastGeneratedAt: new Date().toISOString(),
      generationSummary: `Auto-generated at ${now.toISO()} with ${topArticles.length} article(s).`,
      topArticles: topArticles.map((article) => ({
        post: article.postId,
        title: article.title,
        summary: article.summary,
        url: article.url,
        views: article.views,
        imageUrl: article.imageUrl,
      })),
    }

    const existing = await req.payload.find({
      collection: 'newsletterCampaigns',
      where: {
        and: [{ digestDate: { equals: digestDate } }, { autoGenerated: { equals: true } }],
      },
      limit: 1,
    })

    if (existing.totalDocs > 0) {
      const updated = await req.payload.update({
        collection: 'newsletterCampaigns',
        id: existing.docs[0].id,
        data: campaignData,
        overrideAccess: true,
      })

      return {
        output: {
          updatedId: updated.id,
        },
      }
    }

    const created = await req.payload.create({
      collection: 'newsletterCampaigns',
      data: campaignData,
      overrideAccess: true,
    })

    return {
      output: {
        createdId: created.id,
      },
    }
  },
}
