/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    headlineVideos: HeadlineVideo;
    podcastAssets: PodcastAsset;
    podcastBanners: PodcastBanner;
    articleAudio: ArticleAudio;
    blogPosts: BlogPost;
    blogCategories: BlogCategory;
    podcasts: Podcast;
    staging: Staging;
    newsletter: Newsletter;
    newsletterCampaigns: NewsletterCampaign;
    podcastPlaylists: PodcastPlaylist;
    'push-subscriptions': PushSubscription;
    'mobile-push-subscriptions': MobilePushSubscription;
    'notification-logs': NotificationLog;
    dawanpediaEntries: DawanpediaEntry;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    podcastPlaylists: {
      podcasts: 'podcasts';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    headlineVideos: HeadlineVideosSelect<false> | HeadlineVideosSelect<true>;
    podcastAssets: PodcastAssetsSelect<false> | PodcastAssetsSelect<true>;
    podcastBanners: PodcastBannersSelect<false> | PodcastBannersSelect<true>;
    articleAudio: ArticleAudioSelect<false> | ArticleAudioSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    blogCategories: BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    podcasts: PodcastsSelect<false> | PodcastsSelect<true>;
    staging: StagingSelect<false> | StagingSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    newsletterCampaigns: NewsletterCampaignsSelect<false> | NewsletterCampaignsSelect<true>;
    podcastPlaylists: PodcastPlaylistsSelect<false> | PodcastPlaylistsSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'mobile-push-subscriptions': MobilePushSubscriptionsSelect<false> | MobilePushSubscriptionsSelect<true>;
    'notification-logs': NotificationLogsSelect<false> | NotificationLogsSelect<true>;
    dawanpediaEntries: DawanpediaEntriesSelect<false> | DawanpediaEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      sendDailyDigest: TaskSendDailyDigest;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage user accounts and roles for the blog platform. Assign content creator roles to enable post submission workflow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Upload a profile picture for the user.
   */
  profilePicture?: (string | null) | Media;
  /**
   * Select the roles for this user. Content creators can write posts, admins can approve them.
   */
  roles?: ('admin' | 'analyst' | 'columnist' | 'reporter' | 'contributor' | 'user')[] | null;
  /**
   * User subscription level for premium content access.
   */
  subscriptionTier?: ('free' | 'premium') | null;
  /**
   * Automatically updated when user verifies their email.
   */
  isEmailVerified?: boolean | null;
  likedPosts?: (string | BlogPost)[] | null;
  favoritedPosts?: (string | BlogPost)[] | null;
  likedPodcasts?: (string | Podcast)[] | null;
  likedVideos?: (string | HeadlineVideo)[] | null;
  /**
   * Tracks the most recent verification emails sent to this user to prevent abuse.
   */
  verificationEmailRequests?:
    | {
        sentAt: string;
        context?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for images (important for accessibility & SEO)
   */
  alt: string;
  /**
   * Optional caption for the media file
   */
  caption?: string | null;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage blog posts and content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: string;
  name: string;
  /**
   * This is automatically generated from the title.
   */
  slug: string;
  /**
   * Current status of your post. Contact an admin to change this.
   */
  statusDisplay?: string | null;
  /**
   * Change the publication status of this post.
   */
  status?: ('pending' | 'published') | null;
  layout?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richtext';
          }
        | {
            heading: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            subheading: string;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cover';
          }
        | {
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * Upload a video file (MP4, WebM, etc.)
             */
            video: string | HeadlineVideo;
            /**
             * Whether the video should start playing automatically (note: most browsers require videos to be muted for autoplay)
             */
            autoplay?: boolean | null;
            /**
             * Whether the video should be muted by default
             */
            muted?: boolean | null;
            /**
             * Whether to show video player controls (play, pause, volume, etc.)
             */
            controls?: boolean | null;
            /**
             * Whether the video should loop continuously
             */
            loop?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Upload a PDF document
             */
            pdf: string | Media;
            /**
             * Whether to display a download button for the PDF
             */
            showDownloadButton?: boolean | null;
            /**
             * Whether to show an embedded preview of the PDF (may not work on all devices)
             */
            showPreview?: boolean | null;
            /**
             * Height of the PDF preview in pixels
             */
            previewHeight?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdf';
          }
        | {
            /**
             * Enter either a URL to embed OR paste the embed HTML code from platforms like Twitter, YouTube, etc.
             */
            content: string;
            /**
             * Optional title for the embedded content
             */
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
      )[]
    | null;
  /**
   * Optional narrated audio uploaded manually. You can add or replace later.
   */
  articleAudio?: (string | null) | ArticleAudio;
  /**
   * Select countries related to this article.
   */
  countryTags?: ('International' | 'Somalia' | 'Kenya' | 'Djibouti' | 'Ethiopia' | 'Eritrea')[] | null;
  categories?: (string | BlogCategory)[] | null;
  /**
   * Check this to manually enter reporter details instead of selecting a user account.
   */
  useManualReporter?: boolean | null;
  /**
   * Enter the details of the external reporter for this article.
   */
  manualReporter?: {
    /**
     * Full name of the reporter
     */
    name: string;
    /**
     * Check this to enter a custom role instead of selecting from predefined options.
     */
    useCustomRole?: boolean | null;
    role?:
      | (
          | 'reporter'
          | 'correspondent'
          | 'freelance'
          | 'contributor'
          | 'special-correspondent'
          | 'field-reporter'
          | 'investigative'
          | 'analyst'
          | 'senior-correspondent'
          | 'bureau-chief'
        )
      | null;
    /**
     * Enter a custom role title for the reporter.
     */
    customRole?: string | null;
  };
  /**
   * Select an author from content creators and admins. Regular users are excluded.
   */
  author?: (string | null) | User;
  likes?: number | null;
  favoritesCount?: number | null;
  views?: number | null;
  isEditorsPick?: boolean | null;
  /**
   * Check this to feature this post on the homepage.
   */
  featuredinhomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headlineVideos".
 */
export interface HeadlineVideo {
  id: string;
  /**
   * Internal label shown in the media library.
   */
  title: string;
  /**
   * Optional notes or synopsis for the uploaded episode.
   */
  description: string;
  /**
   * Upload a thumbnail image for this video.
   */
  thumbnail: string | Media;
  views?: number | null;
  likes?: number | null;
  bunnyVideoId?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Narrated article audio uploads.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articleAudio".
 */
export interface ArticleAudio {
  id: string;
  /**
   * Optional label to help editors find article narrations.
   */
  title?: string | null;
  description?: string | null;
  bunnyVideoId?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories".
 */
export interface BlogCategory {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts".
 */
export interface Podcast {
  id: string;
  title: string;
  slug: string;
  description: string;
  media: string | PodcastAsset;
  mediaType?: ('audio' | 'video') | null;
  playlist?: (string | null) | PodcastPlaylist;
  episodeNumber?: number | null;
  categories?: (string | BlogCategory)[] | null;
  peopleInvolved?:
    | {
        name: string;
        role: 'host' | 'co-host' | 'guest' | 'interviewer' | 'producer' | 'editor' | 'sound-engineer' | 'moderator';
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  coverImage: string | Media;
  publishedAt?: string | null;
  isPublished?: boolean | null;
  playCount?: number | null;
  likes?: number | null;
  externalLinks?:
    | {
        title: string;
        url: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcastAssets".
 */
export interface PodcastAsset {
  id: string;
  bunnyVideoId?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcastPlaylists".
 */
export interface PodcastPlaylist {
  id: string;
  name: string;
  slug: string;
  image: string | Media;
  podcasts?: {
    docs?: (string | Podcast)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload coming soon podcast banners (strictly 1280x720 pixels).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcastBanners".
 */
export interface PodcastBanner {
  id: string;
  title: string;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Review and approve blog posts submitted by content creators. Simple workflow for content approval.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staging".
 */
export interface Staging {
  id: string;
  blogPost: string | BlogPost;
  status: 'pending' | 'published';
  submittedAt?: string | null;
  submittedBy?: (string | null) | User;
  reviewedBy?: (string | null) | User;
  reviewedAt?: string | null;
  workflowHistory?:
    | {
        action: string;
        performedBy: string | User;
        performedAt: string;
        fromStatus?: string | null;
        toStatus?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  source?: ('popup' | 'footer' | 'website' | 'import' | 'admin') | null;
  subscribedAt?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  preferences?: {
    frequency?: ('daily' | 'weekly' | 'monthly') | null;
    categories?:
      | {
          category: string | BlogCategory;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterCampaigns".
 */
export interface NewsletterCampaign {
  id: string;
  subject: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Automatically populated each evening with the 5 most viewed stories.
   */
  topArticles?:
    | {
        post?: (string | null) | BlogPost;
        title: string;
        summary?: string | null;
        url: string;
        views?: number | null;
        /**
         * Optional hero image URL for this article.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  digestDate?: string | null;
  /**
   * Indicates whether this campaign was prepared by the nightly job.
   */
  autoGenerated?: boolean | null;
  lastGeneratedAt?: string | null;
  generationSummary?: string | null;
  status?: ('draft' | 'send_now' | 'sent' | 'failed') | null;
  sentAt?: string | null;
  sentCount?: number | null;
  failedCount?: number | null;
  errorLog?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores user subscriptions for push notifications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: string;
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores Expo push tokens for mobile app notifications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mobile-push-subscriptions".
 */
export interface MobilePushSubscription {
  id: string;
  token: string;
  platform: 'ios' | 'android' | 'web';
  user?: (string | null) | User;
  lastActive?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log of sent global push notifications for rate limiting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-logs".
 */
export interface NotificationLog {
  id: string;
  type: string;
  sentAt: string;
  timeBlock: 'morning' | 'afternoon' | 'evening';
  articleSlug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Structured people and business profiles for the Dawanpedia knowledge hub.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dawanpediaEntries".
 */
export interface DawanpediaEntry {
  id: string;
  name: string;
  /**
   * Auto-generated from the title.
   */
  slug: string;
  status?: ('draft' | 'review' | 'published') | null;
  /**
   * Required when the entry status is set to Published.
   */
  publishedDate?: string | null;
  entryType: 'person' | 'business';
  /**
   * Optional profile image shown alongside the header.
   */
  primaryImage?: (string | null) | Media;
  /**
   * Quick facts displayed under the profile header.
   */
  profileFacts?:
    | {
        label: string;
        value: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Stack of narrative sections for this entry.
   */
  sections: {
    heading: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * Canonical references for this entry.
   */
  references?:
    | {
        title: string;
        publication?: string | null;
        url: string;
        accessedDate?: string | null;
        citationText?: string | null;
        type?: ('article' | 'official-document' | 'press-release' | 'interview' | 'report' | 'other') | null;
        /**
         * Link to another Dawanpedia entry if this source refers to an internal profile.
         */
        relatedEntry?: (string | null) | DawanpediaEntry;
        verification?: {
          status?: ('unchecked' | 'valid' | 'broken') | null;
          checkedAt?: string | null;
          notes?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  externalResources?:
    | {
        label: string;
        url: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedContent?: {
    blogPosts?: (string | BlogPost)[] | null;
    /**
     * Optional cross-links to other relevant Dawanpedia entries.
     */
    relatedEntries?: (string | DawanpediaEntry)[] | null;
  };
  /**
   * Internal notes for editors and reviewers.
   */
  editorialNotes?: string | null;
  changelog?:
    | {
        label: string;
        description?: string | null;
        updatedAt?: string | null;
        updatedBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  workflow?: {
    /**
     * Primary editor responsible for this entry.
     */
    maintainer?: (string | null) | User;
    lastReviewedBy?: (string | null) | User;
    lastReviewedAt?: string | null;
    potentialDuplicateOf?: (string | null) | DawanpediaEntry;
    /**
     * Optional 0-1 confidence score for duplicate detection.
     */
    duplicateConfidence?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendDailyDigest';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendDailyDigest') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'headlineVideos';
        value: string | HeadlineVideo;
      } | null)
    | ({
        relationTo: 'podcastAssets';
        value: string | PodcastAsset;
      } | null)
    | ({
        relationTo: 'podcastBanners';
        value: string | PodcastBanner;
      } | null)
    | ({
        relationTo: 'articleAudio';
        value: string | ArticleAudio;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'blogCategories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'podcasts';
        value: string | Podcast;
      } | null)
    | ({
        relationTo: 'staging';
        value: string | Staging;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: string | Newsletter;
      } | null)
    | ({
        relationTo: 'newsletterCampaigns';
        value: string | NewsletterCampaign;
      } | null)
    | ({
        relationTo: 'podcastPlaylists';
        value: string | PodcastPlaylist;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: string | PushSubscription;
      } | null)
    | ({
        relationTo: 'mobile-push-subscriptions';
        value: string | MobilePushSubscription;
      } | null)
    | ({
        relationTo: 'notification-logs';
        value: string | NotificationLog;
      } | null)
    | ({
        relationTo: 'dawanpediaEntries';
        value: string | DawanpediaEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  profilePicture?: T;
  roles?: T;
  subscriptionTier?: T;
  isEmailVerified?: T;
  likedPosts?: T;
  favoritedPosts?: T;
  likedPodcasts?: T;
  likedVideos?: T;
  verificationEmailRequests?:
    | T
    | {
        sentAt?: T;
        context?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headlineVideos_select".
 */
export interface HeadlineVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  thumbnail?: T;
  views?: T;
  likes?: T;
  bunnyVideoId?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcastAssets_select".
 */
export interface PodcastAssetsSelect<T extends boolean = true> {
  bunnyVideoId?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcastBanners_select".
 */
export interface PodcastBannersSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articleAudio_select".
 */
export interface ArticleAudioSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  bunnyVideoId?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  statusDisplay?: T;
  status?: T;
  layout?:
    | T
    | {
        richtext?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cover?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              autoplay?: T;
              muted?: T;
              controls?: T;
              loop?: T;
              id?: T;
              blockName?: T;
            };
        pdf?:
          | T
          | {
              pdf?: T;
              showDownloadButton?: T;
              showPreview?: T;
              previewHeight?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              content?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
      };
  articleAudio?: T;
  countryTags?: T;
  categories?: T;
  useManualReporter?: T;
  manualReporter?:
    | T
    | {
        name?: T;
        useCustomRole?: T;
        role?: T;
        customRole?: T;
      };
  author?: T;
  likes?: T;
  favoritesCount?: T;
  views?: T;
  isEditorsPick?: T;
  featuredinhomepage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts_select".
 */
export interface PodcastsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  media?: T;
  mediaType?: T;
  playlist?: T;
  episodeNumber?: T;
  categories?: T;
  peopleInvolved?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        id?: T;
      };
  coverImage?: T;
  publishedAt?: T;
  isPublished?: T;
  playCount?: T;
  likes?: T;
  externalLinks?:
    | T
    | {
        title?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staging_select".
 */
export interface StagingSelect<T extends boolean = true> {
  blogPost?: T;
  status?: T;
  submittedAt?: T;
  submittedBy?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  workflowHistory?:
    | T
    | {
        action?: T;
        performedBy?: T;
        performedAt?: T;
        fromStatus?: T;
        toStatus?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  source?: T;
  subscribedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  preferences?:
    | T
    | {
        frequency?: T;
        categories?:
          | T
          | {
              category?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterCampaigns_select".
 */
export interface NewsletterCampaignsSelect<T extends boolean = true> {
  subject?: T;
  content?: T;
  topArticles?:
    | T
    | {
        post?: T;
        title?: T;
        summary?: T;
        url?: T;
        views?: T;
        imageUrl?: T;
        id?: T;
      };
  digestDate?: T;
  autoGenerated?: T;
  lastGeneratedAt?: T;
  generationSummary?: T;
  status?: T;
  sentAt?: T;
  sentCount?: T;
  failedCount?: T;
  errorLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcastPlaylists_select".
 */
export interface PodcastPlaylistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  podcasts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  endpoint?: T;
  keys?:
    | T
    | {
        p256dh?: T;
        auth?: T;
      };
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mobile-push-subscriptions_select".
 */
export interface MobilePushSubscriptionsSelect<T extends boolean = true> {
  token?: T;
  platform?: T;
  user?: T;
  lastActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-logs_select".
 */
export interface NotificationLogsSelect<T extends boolean = true> {
  type?: T;
  sentAt?: T;
  timeBlock?: T;
  articleSlug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dawanpediaEntries_select".
 */
export interface DawanpediaEntriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  entryType?: T;
  primaryImage?: T;
  profileFacts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  references?:
    | T
    | {
        title?: T;
        publication?: T;
        url?: T;
        accessedDate?: T;
        citationText?: T;
        type?: T;
        relatedEntry?: T;
        verification?:
          | T
          | {
              status?: T;
              checkedAt?: T;
              notes?: T;
            };
        id?: T;
      };
  externalResources?:
    | T
    | {
        label?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  relatedContent?:
    | T
    | {
        blogPosts?: T;
        relatedEntries?: T;
      };
  editorialNotes?: T;
  changelog?:
    | T
    | {
        label?: T;
        description?: T;
        updatedAt?: T;
        updatedBy?: T;
        id?: T;
      };
  workflow?:
    | T
    | {
        maintainer?: T;
        lastReviewedBy?: T;
        lastReviewedAt?: T;
        potentialDuplicateOf?: T;
        duplicateConfidence?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendDailyDigest".
 */
export interface TaskSendDailyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}